### ISSUE TITLE
Uncaught exception in alexa-remote2 causes node red to restart

### ISSUE THREAD

**Issue by coppo86** [586837r/node-red-contrib-alexa-remote2#111]
I've been having a few problems with NR since installing alexa-remote2. Node red would restart 2 or 3 times a day. Node red and node set was up to date at the  time as far as i know. I have removed the node set for now and all is stable again.

Can anyone suggest what to look into?

I';m quite willing to believe its something I've done wrong!

This is the log extract.

`Mar 13 18:38:20 raspberrypi Node-RED[356]: 13 Mar 18:38:20 - [red] Uncaught Exception:
Mar 13 18:38:20 raspberrypi Node-RED[356]: 13 Mar 18:38:20 - TypeError: Converting circular structure to JSON
Mar 13 18:38:20 raspberrypi Node-RED[356]:     at JSON.stringify (<anonymous>)
Mar 13 18:38:20 raspberrypi Node-RED[356]:     at WebSocket.websocket.on (/home/pi/.node-red/node_modules/alexa-remote2/alexa-wsmqtt.js:127:111)
Mar 13 18:38:20 raspberrypi Node-RED[356]:     at WebSocket.emit (events.js:182:13)
Mar 13 18:38:20 raspberrypi Node-RED[356]:     at ClientRequest.req.on (/home/pi/.node-red/node_modules/alexa-remote2/node_modules/ws/lib/websocket.js:578:27)
Mar 13 18:38:20 raspberrypi Node-RED[356]:     at ClientRequest.emit (events.js:182:13)
Mar 13 18:38:20 raspberrypi Node-RED[356]:     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:562:21)
Mar 13 18:38:20 raspberrypi Node-RED[356]:     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
Mar 13 18:38:20 raspberrypi Node-RED[356]:     at TLSSocket.socketOnData (_http_client.js:449:20)
Mar 13 18:38:20 raspberrypi Node-RED[356]:     at TLSSocket.emit (events.js:182:13)
Mar 13 18:38:20 raspberrypi Node-RED[356]:     at addChunk (_stream_readable.js:287:12)
Mar 13 18:38:20 raspberrypi Node-RED[356]:     at readableAddChunk (_stream_readable.js:268:11)
Mar 13 18:38:20 raspberrypi Node-RED[356]:     at TLSSocket.Readable.push (_stream_readable.js:223:10)
Mar 13 18:38:20 raspberrypi Node-RED[356]:     at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:122:17)
Mar 13 18:38:20 raspberrypi systemd[1]: nodered.service: Main process exited, code=exited, status=1/FAILURE
Mar 13 18:38:20 raspberrypi systemd[1]: nodered.service: Unit entered failed state.
Mar 13 18:38:20 raspberrypi systemd[1]: nodered.service: Failed with result 'exit-code'.
Mar 13 18:38:20 raspberrypi systemd[1]: nodered.service: Service hold-off time over, scheduling restart.
Mar 13 18:38:20 raspberrypi systemd[1]: Stopped Node-RED graphical event wiring tool.`

**Comment by dissemin8** [comment]
I have the same problem although it only causes my node-red to restart every few days.   I'm a little surprised that it's possible for an installed node to cause nodered to restart. It's a shame node-red cannot handle the exception,

**Comment by UserRG** [comment]
I've got the same Problem. 
Here is my logfile-part:

Mar 13 19:39:13 TaRoCCU3 daemon.err node-red: 13 Mar 19:39:13 - [red] Uncaught Exception:

Mar 13 19:39:13 TaRoCCU3 daemon.err node-red: 13 Mar 19:39:13 - TypeError: Converting circular structure to JSON

Mar 13 19:39:13 TaRoCCU3 daemon.err node-red:     at JSON.stringify (<anonymous>)

Mar 13 19:39:13 TaRoCCU3 daemon.err node-red:     at WebSocket.websocket.on (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-alexa-remote2/node_modules/alexa-remote2/alexa-wsmqtt.js:127:111)
