### ISSUE TITLE
proxy error, docker

### ISSUE THREAD

**Issue by Jmilesy** [586837r/node-red-contrib-alexa-remote2#27]
When i try to use the proxy method i get the following error

```
7 Jul 23:53:27 - [info] Started flows

7 Jul 23:53:28 - [error] [alexa-remote-account:home] Error: ENOENT: no such file or directory, open '/alexa/cookie.json'

7 Jul 23:53:49 - [red] Uncaught Exception:

7 Jul 23:53:49 - Error: listen EADDRINUSE :::1880

    at Server.setupListenHandle [as _listen2] (net.js:1360:14)

    at listenInCluster (net.js:1401:12)

    at Server.listen (net.js:1485:7)
When i try to use the proxy method of authentication I get the following error:
    at Function.listen (/data/node_modules/alexa-cookie2/node_modules/express/lib/application.js:618:24)

    at Object.initAmazonProxy (/data/node_modules/alexa-cookie2/lib/proxy.js:303:22)

    at Object.generateAlexaCookie (/data/node_modules/alexa-cookie2/alexa-cookie.js:354:21)

    at AlexaRemote.generateCookie (/data/node_modules/node-red-contrib-alexa-remote2/tools/tools.js:11:26)

    at getCookie (/data/node_modules/alexa-remote2/alexa-remote.js:103:22)

    at AlexaRemote.init (/data/node_modules/alexa-remote2/alexa-remote.js:138:9)

    at AlexaRemoteAccountNode._initAlexaFromObject (/data/node_modules/node-red-contrib-alexa-remote2/nodes/alexa-remote-account.js:109:15)

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the node-red-docker@1.0.0 start script
```

I then have to roll back to the previous flows.json to be able to access node red.

Am i missing somethings simple?

Many thanks

**Comment by 586837r** [comment]
Make sure that the port is not already used by another Alexa Remote Account or any other application otherwise it will crash. Port 1880 is usually used by node-red so you should choose a different port.

**Comment by 586837r** [comment]
Now (v2.3.4) node-red should no longer crash because of this, you will get a regular error when a port is in use.
