### ISSUE TITLE
Error: failed to initialise smarthome simplified: "no body"

### ISSUE THREAD

**Issue by gusman80** [586837r/node-red-contrib-alexa-remote2#52]
Hey, (maybe related to #40 )

this node is great, but it always stops working for me after some days.
Last time i just re-inited the auth, but TODAY it is not even working anymore after reinit/refresh.

the speak/custom routine node always emits "null" without any errors.
and the info node "Update Cached State" emits:

Error: failed to initialise smarthome simplified: "no body"
    at IncomingMessage.res.on (/home/pi/.node-red/node_modules/alexa-remote2/alexa-remote.js:743:69)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

What am I doing wrong. 

(Using auth method: proxy and saving the auth to file at update intervall of 2 days)

**Comment by 586837r** [comment]
I don't know what could cause it to stop working. Does a *Fresh Authentication* with the *Alexa Init* node help?

**Comment by alexba1** [comment]
Hi, I have the same problem. I got the message, failed to initialise smarthome simplified: "no body"
Authentication is working. 
[info] Node-RED version: v0.19.4
[info] Node.js  version: v8.16.1
[info] Linux 4.19.58-v7+ arm LE

regards Alex
