### ISSUE TITLE
getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by hannemann** [586837r/node-red-contrib-alexa-remote2#69]
Hi,

if i configure a file for the cookie the next time i do a full deploy i get this error:

```
nodered_1  | (node:16) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND alexa-comms-mobile-service.amazon.de	 alexa-comms-mobile-service.amazon.de	:443
nodered_1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
nodered_1  | (node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
nodered_1  | (node:16) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
nodered_1  | 7 Nov 21:57:29 - [error] [alexa-remote-account:5857d31b.25147c] getaddrinfo ENOTFOUND alexa-comms-mobile-service.amazon.de	 alexa-comms-mobile-service.amazon.de	:443
nodered_1  | (node:16) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```
The next time i restart node red i get the same error but node red refuses to start
```
nodered_1  | 6 Nov 23:21:06 - [info] [alexa-remote-account:5857d31b.25147c] intialising with the PROXY method and saved data...
nodered_1  | 6 Nov 23:21:06 - [info] [deconz-server:Phoscon-GW] WebSocket opened
nodered_1  | 6 Nov 23:21:06 - [error] [alexa-home-conf:dc6027d1.09f2e8] Error: connect ECONNREFUSED 34.240.81.189:8883
nodered_1  | (node:16) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND alexa-comms-mobile-service.amazon.de	 alexa-comms-mobile-service.amazon.de	:443
nodered_1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
nodered_1  | (node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
nodered_1  | (node:16) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
nodered_1  | 6 Nov 23:21:07 - [red] Uncaught Exception:
nodered_1  | 6 Nov 23:21:07 - TypeError: Converting circular structure to JSON
nodered_1  |     at JSON.stringify (<anonymous>)
nodered_1  |     at WebSocket.websocket.on (/data/node_modules/alexa-remote2/alexa-wsmqtt.js:127:111)
nodered_1  |     at WebSocket.emit (events.js:198:13)
nodered_1  |     at WebSocket.EventEmitter.emit (domain.js:448:20)
nodered_1  |     at ClientRequest.req.on (/data/node_modules/alexa-remote2/node_modules/ws/lib/websocket.js:594:27)
nodered_1  |     at ClientRequest.emit (events.js:198:13)
nodered_1  |     at ClientRequest.EventEmitter.emit (domain.js:448:20)
nodered_1  |     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
nodered_1  |     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
nodered_1  |     at TLSSocket.socketOnData (_http_client.js:442:20)
nodered_1  |     at TLSSocket.emit (events.js:198:13)
nodered_1  |     at TLSSocket.EventEmitter.emit (domain.js:448:20)
nodered_1  |     at addChunk (_stream_readable.js:288:12)
nodered_1  |     at readableAddChunk (_stream_readable.js:269:11)
nodered_1  |     at TLSSocket.Readable.push (_stream_readable.js:224:10)
nodered_1  |     at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
nodered_1  | npm ERR! code ELIFECYCLE
nodered_1  | npm ERR! errno 1
nodered_1  | npm ERR! node-red-docker@1.0.2 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
nodered_1  | npm ERR! Exit status 1
```
If i ping the address i get answers:
```
bash-4.4# ping alexa-comms-mobile-service.amazon.de
PING d1q0pey6vysipm.cloudfront.net (13.225.79.218) 56(84) bytes of data.
64 bytes from server-13-225-79-218.fra2.r.cloudfront.net (13.225.79.218): icmp_seq=1 ttl=240 time=32.7 ms
64 bytes from server-13-225-79-218.fra2.r.cloudfront.net (13.225.79.218): icmp_seq=2 ttl=240 time=22.7 ms
64 bytes from server-13-225-79-218.fra2.r.cloudfront.net (13.225.79.218): icmp_seq=3 ttl=240 time=23.4 ms
^C
--- d1q0pey6vysipm.cloudfront.net ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 6ms
rtt min/avg/max/mdev = 22.732/26.299/32.723/4.553 ms
```
If i delete the file configuration everything works fine but i have to log in every time i do a full deploy.

I am running node-red-docker:latest on ubuntu 18.04 with alexa-remote2 3.4.1

Do you have any ideas whats wrong?

Henning

**Comment by 586837r** [comment]
Not sure what is going wrong there. Maybe its a system bug like here: https://github.com/nodejs/node/issues/5436.

Anyways the errors are only about the Websocket/Event system. Does it work if you turn off events in the account node configuration?

**Comment by hannemann** [comment]
No, the errors remain the same.

I deleted all docker images and pulled node-red:latest again. I tried to set 8.8.8.8 as DNS in the container with no success.
I also tried to not auto initialize and use a init node. Same error. If i inject a timestamp into the init node node-red crashes.

**Comment by hannemann** [comment]
Finally: trailing whitespace within page configuration...

secondsWaisted.forEach(() => head.desk())

Feature Request: Please trim whitespace... :)

Anyway... thank you for the great node!

Henning
