### ISSUE TITLE
Failure prevents nodered from starting

### ISSUE THREAD

**Issue by wizbowes** [586837r/node-red-contrib-alexa-remote2#85]
Nodered completely won't start.  When running manually I get the following error:

```
24 Dec 16:04:02 - [info] Starting flows
24 Dec 16:04:03 - [error] [pushover:Soil Sensor] No Pushover api token set
24 Dec 16:04:03 - [error] [pushover:Soil Sensor] No Pushover user key set
24 Dec 16:04:05 - [error] [pushover:PushOver Flood Alert] No Pushover api token set
24 Dec 16:04:05 - [error] [pushover:PushOver Flood Alert] No Pushover user key set
24 Dec 16:04:06 - [info] Started flows
24 Dec 16:04:06 - [info] [mqtt-broker:d7c95fbd.460f4] Connected to broker: mqtt://192.168.1.19:1883
24 Dec 16:04:06 - [info] [mqtt-broker:Snips] Connected to broker: mqtt://192.168.1.17:1883
24 Dec 16:04:06 - [info] [alexa-remote-account:46cf25.1ac880dc] intialising with the PROXY method and saved data...     24 Dec 16:04:06 - [info] [server:Home Assistant] WebSocket Connected to http://192.168.1.19:8123
(node:1807) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND alexa-comms-mobile-service.amazon.co.uk      alexa-comms-mobile-service.amazon.co.uk :443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
(node:1807) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1807) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
24 Dec 16:04:07 - [red] Uncaught Exception:
24 Dec 16:04:07 - TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at WebSocket.websocket.on (/home/pi/.node-red/node_modules/alexa-remote2/alexa-wsmqtt.js:127:111)
    at WebSocket.emit (events.js:189:13)
    at ClientRequest.req.on (/home/pi/.node-red/node_modules/ws/lib/websocket.js:594:27)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

I'm unable to remove the node from the front end as it won't start - going to work out how to remove it from the cli.

**Comment by wizbowes** [comment]
Note:  For those suffering from the same issue - I deleted the cookie file and node-red can now start.
